[package]
name = "proxy-info"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["rustls"] }
tokio = { version = "1.0", features = ["full"] }
eyre = "0.6"
clap = { version = "4.4", features = ["derive"] }
hex = "0.4"
